version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  go_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - jobs-data:/tmp
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_PORT=5672
      - FILESTORAGE_HOST=file-storage
      - FILESTORAGE_PORT=8888
      - DOCKER_HOST=unix:///var/run/docker.sock
  file-storage:
    image: file-storage
    pull_policy: never
    container_name: file-storage
    ports:
      - "8888:8888"

volumes:
  rabbitmq_data:
  jobs-data:
