#!/usr/bin/env bash
set -euo pipefail

# Minimal generate_mocks.sh
# - Only a list of interfaces and calls to mockgen
# - Produces a single combined file at tests/mocks/mocks_generated.go

OUTPUT="tests/mocks/mocks_generated.go"
PACKAGE="mocks"

INTERFACES=(
	"internal/rabbitmq/channel Channel"
	"internal/rabbitmq/responder Responder"
	"internal/scheduler Scheduler"
	"internal/stages/compiler Compiler"
	"internal/stages/executor Executor"
	"internal/stages/packager Packager"
	"internal/stages/verifier Verifier"
	"internal/storage Storage"
	"internal/pipeline Worker"
	"internal/docker DockerClient"
)


tmpdir=$(mktemp -d)
trap 'rm -rf "$tmpdir"' EXIT

mkdir -p "$(dirname "$OUTPUT")"

imports_file="$tmpdir/_imports.txt"
bodies_file="$tmpdir/_bodies.go"
>"$imports_file"
>"$bodies_file"

for entry in "${INTERFACES[@]}"; do
	pkg="${entry% *}"
	iface="${entry##* }"
	tmp="$tmpdir/mock.tmp"
	mockgen "$(pwd)/$pkg" "$iface" > "$tmp"

	# extract imports (block or single-line) and append to imports_file
	if grep -q '^import (' "$tmp"; then
		sed -n '/^import (/,/)/p' "$tmp" | sed '1d;$d' >> "$imports_file"
	fi
	if grep -q '^import \"' "$tmp"; then
		grep '^import \"' "$tmp" | sed 's/^import //' >> "$imports_file"
	fi

	# extract body (everything after package and imports)
	awk '
		BEGIN{in_import=0}
		/^package /{next}
		/^import[[:space:]]*\(/ {in_import=1; next}
		in_import && /^\)/{in_import=0; next}
		in_import{next}
		/^import[[:space:]]*".*"$/ {next}
		{print}
	' "$tmp" >> "$bodies_file"
	echo >> "$bodies_file"
done

# write final output with deduped imports
{
	echo "// Code generated by generate_mocks.sh; DO NOT EDIT."
	echo
	echo "package $PACKAGE"
	echo
	if [ -s "$imports_file" ]; then
		echo "import ("
		sort -u "$imports_file" | sed 's/^/\t/'
		echo ")"
		echo
	fi
	cat "$bodies_file"
} > "$OUTPUT"

echo "Generated mocks in $OUTPUT"
