// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/rabbitmq/responder (interfaces: Responder)
//
// Generated by this command:
//
//	mockgen --destination ./tests/mocks/responder/mockgen.go ./internal/rabbitmq/responder Responder
//

// Package mock_responder is a generated GoMock package.
package mock_responder

import (
	reflect "reflect"

	languages "github.com/mini-maxit/worker/pkg/languages"
	messages "github.com/mini-maxit/worker/pkg/messages"
	solution "github.com/mini-maxit/worker/pkg/solution"
	amqp091 "github.com/rabbitmq/amqp091-go"
	gomock "go.uber.org/mock/gomock"
)

// MockResponder is a mock of Responder interface.
type MockResponder struct {
	ctrl     *gomock.Controller
	recorder *MockResponderMockRecorder
	isgomock struct{}
}

// MockResponderMockRecorder is the mock recorder for MockResponder.
type MockResponderMockRecorder struct {
	mock *MockResponder
}

// NewMockResponder creates a new mock instance.
func NewMockResponder(ctrl *gomock.Controller) *MockResponder {
	mock := &MockResponder{ctrl: ctrl}
	mock.recorder = &MockResponderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResponder) EXPECT() *MockResponderMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockResponder) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockResponderMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockResponder)(nil).Close))
}

// Publish mocks base method.
func (m *MockResponder) Publish(queueName string, publishing amqp091.Publishing) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", queueName, publishing)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockResponderMockRecorder) Publish(queueName, publishing any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockResponder)(nil).Publish), queueName, publishing)
}

// PublishErrorToResponseQueue mocks base method.
func (m *MockResponder) PublishErrorToResponseQueue(messageType, messageID, responseQueue string, err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PublishErrorToResponseQueue", messageType, messageID, responseQueue, err)
}

// PublishErrorToResponseQueue indicates an expected call of PublishErrorToResponseQueue.
func (mr *MockResponderMockRecorder) PublishErrorToResponseQueue(messageType, messageID, responseQueue, err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishErrorToResponseQueue", reflect.TypeOf((*MockResponder)(nil).PublishErrorToResponseQueue), messageType, messageID, responseQueue, err)
}

// PublishPayloadTaskRespond mocks base method.
func (m *MockResponder) PublishPayloadTaskRespond(messageType, messageID, responseQueue string, taskResult solution.Result) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishPayloadTaskRespond", messageType, messageID, responseQueue, taskResult)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishPayloadTaskRespond indicates an expected call of PublishPayloadTaskRespond.
func (mr *MockResponderMockRecorder) PublishPayloadTaskRespond(messageType, messageID, responseQueue, taskResult any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishPayloadTaskRespond", reflect.TypeOf((*MockResponder)(nil).PublishPayloadTaskRespond), messageType, messageID, responseQueue, taskResult)
}

// PublishSuccessHandshakeRespond mocks base method.
func (m *MockResponder) PublishSuccessHandshakeRespond(messageType, messageID, responseQueue string, languageSpecs []languages.LanguageSpec) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishSuccessHandshakeRespond", messageType, messageID, responseQueue, languageSpecs)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishSuccessHandshakeRespond indicates an expected call of PublishSuccessHandshakeRespond.
func (mr *MockResponderMockRecorder) PublishSuccessHandshakeRespond(messageType, messageID, responseQueue, languageSpecs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishSuccessHandshakeRespond", reflect.TypeOf((*MockResponder)(nil).PublishSuccessHandshakeRespond), messageType, messageID, responseQueue, languageSpecs)
}

// PublishSuccessStatusRespond mocks base method.
func (m *MockResponder) PublishSuccessStatusRespond(messageType, messageID, responseQueue string, status messages.ResponseWorkerStatusPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishSuccessStatusRespond", messageType, messageID, responseQueue, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishSuccessStatusRespond indicates an expected call of PublishSuccessStatusRespond.
func (mr *MockResponderMockRecorder) PublishSuccessStatusRespond(messageType, messageID, responseQueue, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishSuccessStatusRespond", reflect.TypeOf((*MockResponder)(nil).PublishSuccessStatusRespond), messageType, messageID, responseQueue, status)
}
