// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/scheduler (interfaces: Scheduler)
//
// Generated by this command:
//
//	mockgen --destination ./tests/mocks/scheduler/mockgen.go ./internal/scheduler Scheduler
//

// Package mock_scheduler is a generated GoMock package.
package mock_scheduler

import (
	reflect "reflect"

	messages "github.com/mini-maxit/worker/pkg/messages"
	gomock "go.uber.org/mock/gomock"
)

// MockScheduler is a mock of Scheduler interface.
type MockScheduler struct {
	ctrl     *gomock.Controller
	recorder *MockSchedulerMockRecorder
	isgomock struct{}
}

// MockSchedulerMockRecorder is the mock recorder for MockScheduler.
type MockSchedulerMockRecorder struct {
	mock *MockScheduler
}

// NewMockScheduler creates a new mock instance.
func NewMockScheduler(ctrl *gomock.Controller) *MockScheduler {
	mock := &MockScheduler{ctrl: ctrl}
	mock.recorder = &MockSchedulerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScheduler) EXPECT() *MockSchedulerMockRecorder {
	return m.recorder
}

// GetWorkersStatus mocks base method.
func (m *MockScheduler) GetWorkersStatus() map[string]any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkersStatus")
	ret0, _ := ret[0].(map[string]any)
	return ret0
}

// GetWorkersStatus indicates an expected call of GetWorkersStatus.
func (mr *MockSchedulerMockRecorder) GetWorkersStatus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkersStatus", reflect.TypeOf((*MockScheduler)(nil).GetWorkersStatus))
}

// ProcessTask mocks base method.
func (m *MockScheduler) ProcessTask(responseQueueName, messageID string, task *messages.TaskQueueMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessTask", responseQueueName, messageID, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessTask indicates an expected call of ProcessTask.
func (mr *MockSchedulerMockRecorder) ProcessTask(responseQueueName, messageID, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessTask", reflect.TypeOf((*MockScheduler)(nil).ProcessTask), responseQueueName, messageID, task)
}
