name: pre-commit

on: push

jobs:
  run-linters:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Install dependency tools
        run: go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest | go install golang.org/x/tools/cmd/goimports@latest

      - name: Set up pre-commit Cache
        uses: pre-commit/action@v3.0.1
